=== AppFair/appfair.github.io/appsource-schema.json
{
  "$schema": "http://json-schema.org/draft-05/schema#",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The title of this app source catalog."
    },
    "identifier": {
      "type": "string",
      "description": "The unique identifier for this catalog."
    },
    "locale": {
      "type": "string",
      "description": "The name of the locale for the base catalog (IETF BCP 47 language tag)."
    },
    "sourceURL": {
      "type": "string",
      "description": "The canonical URL for this catalog"
    },
    "iconURL": {
      "type": "string",
      "description": "A URL pointing to an icon that can be used to represent the catalog."
    },
    "tintColor": {
      "type": "string",
      "description": "An RGB hex code that suggests how a catalog browser app might style the catalog."
    },
    "localizedDescription": {
      "type": "string",
      "description": "A full description of this catalog. Limited markdown is permitted."
    },
    "apps": {
      "type": "array",
      "description": "A list of the apps available in this catalog, ordered by the default ranking for the catalog.",
      "items": [
        {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "The name for this app."
            },
            "subtitle": {
              "type": "string",
              "description": "A subtitle for the app."
            },
            "localizedDescription": {
              "type": "string",
              "description": "A full description of this app. Limited markdown is permitted."
            },
            "developerName": {
              "type": "string",
              "description": "The name and e-mail address of the developer."
            },
            "bundleIdentifier": {
              "type": "string",
              "description": "The unique identifier for this app."
            },
            "iconURL": {
              "type": "string",
              "description": "A URL pointing to a PNG of the icon for the app."
            },
            "tintColor": {
              "type": "string",
              "description": "An RGB hex code that suggests how a catalog browser app might style the app."
            },
            "version": {
              "type": "string",
              "description": "The version of the app."
            },
            "versionDate": {
              "type": "string",
              "description": "The date when the specified version was released."
            },
            "versionDescription": {
              "type": "string",
              "description": "The description of the version, such as release notes or a change log. Limited markdown permitted."
            },
            "downloadURL": {
              "type": "string",
              "description": "The canonical link to download this app."
            },
            "sha256": {
              "type": "string",
              "description": "The SHA-256 checksum of the app download artifact."
            },
            "size": {
              "type": "integer",
              "description": "The size in bytes of the app download artifact."
            },
            "screenshotURLs": {
              "type": "array",
              "description": "A list of URLs pointing to screenshots of the app.",
              "items": [
                {
                  "type": "string"
                }
              ]
            },
            "localizations": {
              "type": "object",
              "description": "A map of localization keys to a value that is either a URL or else an inline catalog whose values are in the locale's language."
            },
            "permissions": {
              "type": "array",
              "description": "A list of system-level permissions that ths app may request or utilize.",
              "items": [
                {
                  "type": "object",
                  "description": "A single permission",
                  "properties": {
                    "type": {
                      "type": "string",
                      "description": "The type of permission, such as usage, entitlement, or background-mode."
                    },
                    "identifier": {
                      "type": "string",
                      "description": "The type-specific identifier for the permission, such as the usage description key, the entitlement key, or the background mode name."
                    },
                    "usageDescription": {
                      "type": "string",
                      "description": "The description displayed to the end-user about the reason the app wants to use the given permission."
                    }
                  },
                  "required": [
                    "type",
                    "identifier",
                    "usageDescription"
                  ]
                }
              ]
            },
            "fundingLinks": {
              "type": "array",
              "description": "A list of links to funding sources for this app.",
              "items": [
                {
                  "type": "object",
                  "description": "A single funding source for the app.",
                  "properties": {
                    "platform": {
                      "type": "string",
                      "description": "The platform title for the funding souce."
                    },
                    "url": {
                      "type": "string",
                      "description": "The URL to the source-specific funding page for the given app developer."
                    },
                    "localizedTitle": {
                      "type": "string",
                      "description": "The title of the funding campaign."
                    },
                    "localizedDescription": {
                      "type": "string",
                      "description": "A full description of the funding campaign. Limited markdown permitted."
                    }
                  },
                  "required": [
                    "platform",
                    "url",
                    "localizedTitle",
                    "localizedDescription"
                  ]
                }
              ]
            }
          },
          "required": [
            "name",
            "bundleIdentifier",
            "version",
            "downloadURL",
            "sha256",
            "size"
          ]
        }
      ]
    }
  },
  "required": [
    "name",
    "identifier",
    "apps"
  ]
}

=== AppFair/appfair.github.io/fairapps-altstore.json
{
  "apps": [
    {
      "beta": false,
      "bundleIdentifier": "app.Stanza-Redux",
      "categories": [
        "public.app-category.reference"
      ],
      "coreSize": 102480,
      "developerName": "fairapps <fairapps@appfair.org>",
      "downloadCount": 3,
      "downloadURL": "https://github.com/Stanza-Redux/App/releases/download/0.3.17/Stanza-Redux-iOS.ipa",
      "iconURL": "https://github.com/Stanza-Redux/App/releases/download/0.3.17/Stanza-Redux.png",
      "impressionCount": 6,
      "issueCount": 0,
      "localizedDescription": "An electronic book reader",
      "metadataURL": "https://github.com/Stanza-Redux/App/releases/download/0.3.17/Info.plist#b4b90e72faeb599141e8e95da4ed7868d2e158f3d8848c2eee29a5c5d47d070b",
      "name": "Stanza Redux",
      "permissions": [
        {
          "type": "network.client",
          "usageDescription": "This app needs to access the network in order to download books"
        },
        {
          "type": "files.user-selected.read-write",
          "usageDescription": "This app needs to read epub files and save bookmark progress"
        }
      ],
      "readmeURL": "https://github.com/Stanza-Redux/App/releases/download/0.3.17/README.md#35ad623f3f981e1df9c6a71e324ed8766c66b272630b4e56f61ae856092de3bc",
      "screenshotURLs": [
        "https://github.com/Stanza-Redux/App/releases/download/0.3.17/screenshot_01-iphone-750x1334.png",
        "https://github.com/Stanza-Redux/App/releases/download/0.3.17/screenshot_02-iphone-750x1334.png",
        "https://github.com/Stanza-Redux/App/releases/download/0.3.17/screenshot_03-iphone-750x1334.png",
        "https://github.com/Stanza-Redux/App/releases/download/0.3.17/screenshot_04-iphone-750x1334.png",
        "https://github.com/Stanza-Redux/App/releases/download/0.3.17/screenshot_05-iphone-750x1334.png"
      ],
      "sha256": "10eb4a942d8d801494f21c9b6b036ea0320822b685ccef4e2dd59225e6b1804c",
      "size": 8328869,
      "starCount": 0,
      "subtitle": "An electronic book reader",
      "tintColor": "00375C",
      "version": "0.3.17",
      "versionDate": "2022-05-05T20:39:51Z",
      "versionDescription": "Release 0.3.17",
      "viewCount": 1,
      "watcherCount": 0
    },
    {
      "beta": false,
      "bundleIdentifier": "app.Tune-Out",
      "categories": [
        "public.app-category.music"
      ],
      "coreSize": 103112,
      "developerName": "fairapps <fairapps@appfair.org>",
      "downloadCount": 1,
      "downloadURL": "https://github.com/Tune-Out/App/releases/download/0.8.430/Tune-Out-iOS.ipa",
      "iconURL": "https://github.com/Tune-Out/App/releases/download/0.8.430/Tune-Out.png",
      "impressionCount": 100,
      "issueCount": 0,
      "localizedDescription": "Stream Internet Radio",
      "metadataURL": "https://github.com/Tune-Out/App/releases/download/0.8.430/Info.plist#ec57c2f0b0592e58a706d3f7dae4f3b6c3c56500286c25446cf9fe7b614a6552",
      "name": "Tune Out",
      "permissions": [
        {
          "type": "network.client",
          "usageDescription": "This app needs to access the network in order to stream internet radio stations."
        }
      ],
      "readmeURL": "https://github.com/Tune-Out/App/releases/download/0.8.430/README.md#60ac0e9bc21e80204b0b588b0d89fc0678d0462f8c3d572b713b4e7db4d7896a",
      "screenshotURLs": [
        "https://github.com/Tune-Out/App/releases/download/0.8.430/screenshot_01-iphone-1170x2532.png",
        "https://github.com/Tune-Out/App/releases/download/0.8.430/screenshot_02-iphone-1170x2532.png",
        "https://github.com/Tune-Out/App/releases/download/0.8.430/screenshot_03-iphone-1170x2532.png"
      ],
      "sha256": "fe1398fb20726aa32a34a3766a96ad37eea80f89b1220c0a9ce54609bb71c42f",
      "size": 17244108,
      "starCount": 0,
      "subtitle": "Stream Internet Radio",
      "tintColor": "32ADE6",
      "version": "0.8.430",
      "versionDate": "2022-04-20T15:15:12Z",
      "versionDescription": "Release 0.8.430",
      "viewCount": 10,
      "watcherCount": 0
    }
  ],
  "identifier": "appfair",
  "name": "The App Fair",
  "sourceURL": "https://www.appfair.net/fairapps-altstore.json"
}
